PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CURRENCIES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE VARCHAR(3) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(50) NOT NULL,
    SIGN VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS EXCHANGE_RATES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BASE_CURRENCY_ID INTEGER NOT NULL,
    TARGET_CURRENCY_ID INTEGER NOT NULL,
    RATE REAL NOT NULL,
    FOREIGN KEY (BASE_CURRENCY_ID) REFERENCES CURRENCIES(ID),
    FOREIGN KEY (TARGET_CURRENCY_ID) REFERENCES CURRENCIES(ID),
    UNIQUE (BASE_CURRENCY_ID, TARGET_CURRENCY_ID),
    CHECK(BASE_CURRENCY_ID != TARGET_CURRENCY_ID)
);

INSERT OR IGNORE INTO CURRENCIES (CODE, FULL_NAME, SIGN) VALUES
    ('RUB', 'Russian Ruble', '₽'),
    ('USD', 'United States Dollar', '$'),
    ('EUR', 'Euro', '€');

INSERT OR IGNORE INTO EXCHANGE_RATES (BASE_CURRENCY_ID, TARGET_CURRENCY_ID, RATE) VALUES
  (1, 2, 0.8584),  -- USD to EUR
  (2, 1, 1.17),  -- EUR to USD
  (1, 3, 76.09); -- USD to RUB